### ISSUE TITLE
Generation of Enumeration

### ISSUE THREAD

**Issue by fahimsabir-colt** [Amartus/SonataBlendingTool#5]
When importing schemas to bind items like Address types, or Product Configuration types, it would be really useful if the tool could create an enumeration in addition to the discriminator so that enumeration would also be created when the output is put through a codegen to generate a server stub.  Is this possible?

Rather than this:

```
      properties:
        '@type':
          type: string
          description: The name of the type that uniquely identifies the type of the product that is the subject of the POQ Request. In case of MEF product this is the URN provided in the Product Specification.
      description: MEFProductConfiguration is used as an extension point for MEF specific product/service payload. The `@type` attribute is used as a discriminator
      discriminator:
        propertyName: '@type'
        mapping:
          urn:mef:lso:spec:sonata:access-eline:v2.0.0:poq: '#/components/schemas/AccessEline'
          urn:mef:lso:spec:sonata:carrier-ethernet-operator-uni:v2.0.0:poq: '#/components/schemas/CarrierEthernetOperatorUni'
```

This instead:

```
      properties:
        '@type':
          type: string
          enum:
          - urn:mef:lso:spec:sonata:access-eline:v2.0.0:poq
          - urn:mef:lso:spec:sonata:carrier-ethernet-operator-uni:v2.0.0:poq
          description: The name of the type that uniquely identifies the type of the product that is the subject of the POQ Request. In case of MEF product this is the URN provided in the Product Specification.
      description: MEFProductConfiguration is used as an extension point for MEF specific product/service payload. The `@type` attribute is used as a discriminator
      discriminator:
        propertyName: '@type'
        mapping:
          urn:mef:lso:spec:sonata:access-eline:v2.0.0:poq: '#/components/schemas/AccessEline'
          urn:mef:lso:spec:sonata:carrier-ethernet-operator-uni:v2.0.0:poq: '#/components/schemas/CarrierEthernetOperatorUni'
```
